### ISSUE TITLE
Improve handling of CORS issues

### ISSUE THREAD

**Issue by LarsMichelsen** [tribe29/grafana-checkmk-datasource#1]
In case I configure a site with an old Check_MK version that has missing CORS settings I get this message in the GUI:

Could not read API response, make sure the URL you provided is correct.

The browser console shows this message:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/heute/check_mk/webapi.py?_username=undefined&_secret=undefined&output_format=json&action=get_all_hosts. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Is it possible to detect this specific situation (CORS header issue) and print out another error message?

Something like: Invalid URL or Check_MK version. You need to use at least Check_MK 1.5.0p16.

**Comment by cbmueller** [comment]
Fixed by d8205b5a46363e9b52d97d1fd7e260b1b3f83672.
Unfortunately it is not possible to make a difference between ssl and cors errors. (both are now reflected by the error message)
