### ISSUE TITLE
Set requirements to checkmk enterprise edition (CEE) 

### ISSUE THREAD

**Issue by martinhv** [tribe29/grafana-checkmk-datasource#15]
I think this needs the CMC for being able to run? Thus it will not work with the checkmk Raw Edition.
--> 

Requirements
Minimal Check_MK Version is Check_MK Enterprise Edition (CEE) 1.5.0p16.

**Comment by moschlar** [comment]
Is that so?

[Werk #7341](https://mathias-kettner.com/check_mk-werks.php?werk_id=7341&HTML=yes) is explicitly marked as CRE.

**Comment by kaiserchrss** [comment]
I currently get an error with my CRE Edition. I hope it will be implemented soon...

Object
xhrStatus:"complete"
request:Object
method:"POST"
data:"request={"specification":["template",{"site":null,"service_description":"CPU utilization","host_name":"localhost"}]}"
url:"http://deb-checkmk/main/check_mk/webapi.py?_username=automation&_secret=93faf17e-4d6a-4273-bc9d-4d29cd97c4ab&output_format=json&action=get_graph_recipes"
response:Object
**result:"Check_MK exception: Currently not supported with this Check_MK Edition"**
result_code:1

**Comment by kaiserchrss** [comment]
I currently get an error with my CRE Edition. I hope it will be implemented soon...

Object
xhrStatus:"complete"
request:Object
method:"POST"
data:"request={"specification":["template",{"site":null,"service_description":"CPU utilization","host_name":"localhost"}]}"
url:"[DELETED]/check_mk/webapi.py?_[DELETED]&output_format=json&action=get_graph_recipes"
response:Object
result:"Check_MK exception: Currently not supported with this Check_MK Edition"
result_code:1

**Comment by LarsMichelsen** [comment]
Afaik the intention is to make it available in CRE. We'll have a closer look.

**Comment by superlativo** [comment]
Jus for your information, I've just updated from 1.5.0-16 to 1.5.0-17 and I'm getting the same error...

Object
xhrStatus:"complete"
request:Object
method:"POST"
data:"request={"specification":["template",{"site":"bcbl","service_description":"CPU load","host_name":"Broca17"}]}"
url:"http://kontuz.bcbl.local/bcbl/check_mk/webapi.py?_[DELETED]&output_format=json&action=get_graph_recipes"
response:Object
result:"Check_MK exception: Currently not supported with this Check_MK Edition"
result_code:1

Best,

**Comment by kaiserchrss** [comment]
As for CRE Versions 1.5.0p18 & 1.5.0p19:

Object
xhrStatus:"complete"
request:Object
method:"POST"
data:"request={"specification":["template",{"site":"main","service_description":"PING","host_name":"[REDACTED]"}]}"
url:"http://[REDACTED]/check_mk/webapi.py?_username=[REDACTED]&_secret=[REDACTED]&output_format=json&action=get_graph_recipes"
response:Object
**result:"Check_MK exception: Currently not supported with this Check_MK Edition"**
result_code:1

Still the same error.

**Comment by LarsMichelsen** [comment]
To clarify this issue for the time being: For technical reasons, we can currently only implement the Grafana data source with the CEE/CME. The background is that the Datasource requires features from our enterprise graphing system.

This is the status for the 1.5 and will unfortunately not change with the 1.6. We are thinking about changing this for 1.7, but can't say anything about it yet, because we also have to overcome some technical hurdles along the way.

**Comment by moschlar** [comment]
:disappointed:

**Comment by kaiserchrss** [comment]
There's a workaround that's pretty easy to implement if you're using CRE.
See here:
[click](https://lists.mathias-kettner.de/pipermail/checkmk-en/2018-October/026440.html)

**Comment by LarsMichelsen** [comment]
This workaround is using the PNP4Nagios Grafana connector instead of the Checkmk connector. Right?

**Comment by kaiserchrss** [comment]
Exactly.
