### ISSUE TITLE
Rename Series

### ISSUE THREAD

**Issue by beerygaz** [tribe29/grafana-checkmk-datasource#19]
It's not possible to rename a series, so for instance, adding CPU Utilization from multiple servers or hosts lists each series as "CPU Utilization" with no way to differentiate between them.

![image](https://user-images.githubusercontent.com/10650958/61044041-0a257080-a3d8-11e9-8842-801f644237e9.png)

**Comment by cbmueller** [comment]
This was implemented in c4b175c and will be in the next release ;)
