### ISSUE TITLE
Select aggregation for TCP Connections

### ISSUE THREAD

**Issue by beerygaz** [tribe29/grafana-checkmk-datasource#20]
There is no way to select the aggregation for the TCP Connections service.  It only seems to show **average**.  We need it to show max and min

![image](https://user-images.githubusercontent.com/10650958/61060690-3acad180-a3fb-11e9-95b3-cdf03b2afca5.png)

**Comment by LarsMichelsen** [comment]
Do you mean that you have, for example "State ESTABLISHED" metrics of multiple "TCP connection" services, in a single graph and want to display them as a single metric in a graph?

**Comment by beerygaz** [comment]
Apologies @LarsMichelsen  I meant "selectors" not "aggregation".

 I'm only trying to get the stats for a single service, but I'd like to be able to show the MAXIMUM & MINIMUM values for this metric, but the graph only returns the AVERAGE.  

When selecting form InfluxDB for instance:
![image](https://user-images.githubusercontent.com/10650958/61212900-c7c7a080-a703-11e9-88b6-aa3d8eb688b4.png)

**Comment by LarsMichelsen** [comment]
1.1.0 will contain a "combined graph" feature that can be used to aggregate several services. It'll be released in the next weeks.
