### ISSUE TITLE
Grafana "Service" field is missing on GUI

### ISSUE THREAD

**Issue by Daleio** [tribe29/grafana-checkmk-datasource#21]
Testing  check_mk Check_MK 1.6.0-2019.07.15 Enterprise. Your latest grafana-checkmk-datasource (16July2019). Grafana 6.2.5.
In the Query menu, most fields operate OK including Mode,Site,Host. But "Service" field is inaccessible.

**Comment by cbmueller** [comment]
@Daleio The develop branch is unstable and should not be used. It contains unreleased (and incomplete) features.
@LarsMichelsen Could you please switch the default branch on github to master?

**Comment by Daleio** [comment]
Thank you for the reply.
I will do that.

**Comment by LarsMichelsen** [comment]
done.
