### ISSUE TITLE
docker image don't work

### ISSUE THREAD

**Issue by cryptolukas** [tribe29/grafana-checkmk-datasource#23]
I tried to use the docker image for 1.6.0p2 as CEE and CRE.
Both images don't work properly. I get the following error with 

```
docker run -d -p 8080:50000 checkmk/check-mk-enterprise:1.6.0p2
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

**Comment by LarsMichelsen** [comment]
I think you posted in the wrong project. This is about the Grafana connector of Checkmk.

Have a look at https://checkmk.com/cms_introduction_docker.html on how to use the Checkmk docker container.
