### ISSUE TITLE
Bug: Zero (0) values not displayed correctly

### ISSUE THREAD

**Issue by lw-mgr** [tribe29/grafana-checkmk-datasource#29]
# Abstract
Zero values (0) will not result in a data point in grafana. The graph will falsely display the last received value greater than zero.
![0-value](https://user-images.githubusercontent.com/60145730/72818752-49c4f300-3c6c-11ea-8095-260abf847dda.png)
In CheckMK the graph displays the 0 value correctly.

# Steps to reproduce
- Add CheckMK Check which will could have 0 values (e.g. using fileinfo.groups to count files in a directory, it could be a valid case that the directory is empty)
- Add grafana table panel and use this newly created checkmk service check as datasource
- Grafana only displays rows having value greater than 0

# Versions
- Grafana 6.5.2
-- CheckMK Plugin 1.1.0
- CheckMK 1.6.0p7 Enterprise

**Comment by tuxthepenguin84** [comment]
I can confirm I'm having the same issue.
Grafana 7.0.0
--CheckMK Plugin 1.1.0
CheckMK 1.6.0p10
