### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by klm46** [tribe29/grafana-checkmk-datasource#31]
Hi,

after copieing the Datasource to the plugin-folder and clicking on the new datasource check_mk (without logo by the way) the following Error appears:

> Error: Unexpected token '<' Evaluating http://x.x.x.x:3000/public/app/plugins/datasource/checkmk-datasource/module Loading app/plugins/datasource/checkmk-datasource/module
Data Source Error

Grafana:  v6.6.0 (5c11bbdfb4)
Check_MK: Enterprise 1.6.0p7

Anything to do for me?

**Comment by BenediktSeidl** [comment]
Sadly i have the feeling that this issue is no longer relevant. In the meantime there was a complete rewrite of the plugin which is no longer compatible with 1.6.0
If you still experience this problem, feel free to comment on this issue.

Sorry that it took us so long to respond to your problem.
