### ISSUE TITLE
Allow to scrape views and present them in tables

### ISSUE THREAD

**Issue by fabianlaule** [tribe29/grafana-checkmk-datasource#34]
In addition to graphs and single metrics, it would be good if this datasource also offers the possibility to retrieve views and display them in a table.

Example: To show services with issues on a dashboard, I would like to create specific views with filters in Check_MK and present them in Grafana via the table visualization panel. We are currently implementing this using iFrames, which are unfortunately very inflexible.

**Comment by godspeed-you** [comment]
Hi Fabian,
at the current state and looking at our internal projects, it is not very likely that this enhancement will find his way into the connector. Even though it would be useful. So, I'm sorry to say, that I need to close this issue.
