### ISSUE TITLE
null value and lines connections 

### ISSUE THREAD

**Issue by haytxy** [tribe29/grafana-checkmk-datasource#40]
hello,

"Connect null values" option in Grafana panel settings, won't work if there is no data pulled from the check_mk source. At the end, all points are connected.
like on this graf. Query interval is on 60s like in check_mk (enterprice version).

Tested also the Connect null values/Threshold with <2m settings and nothing has changed

![image](https://user-images.githubusercontent.com/79607995/127651543-c00adeb3-c83f-4842-9f1e-34f2f5f584b5.png)

![image](https://user-images.githubusercontent.com/79607995/127651304-1793bb5b-043a-4d7b-8bfd-98ca2323a319.png)

the goal is to have such graf 
![image](https://user-images.githubusercontent.com/79607995/127651651-c0dc8db0-f314-4bbc-bbcf-7ecd66619430.png)

Is it possible to go around with such a problem?
Maybe I missed some settings? 

Grafana v8.0.4 (81fef5b4b4)
Checkmk enterprice  1.6.0p19

Marcin

**Comment by Myriagone** [comment]
Hello : 
Same problem here
https://forum.checkmk.com/t/bug-checkmk-datasource-with-0-value/28276/4

For me the reason is because the Checkmk data source dont' have **"Fill" option**, like Fill:Null, Fill:zero or other.

We have this option in PNP datasource, InfluxDB datasource ...

Thank you.
