### ISSUE TITLE
Creating complex graphs in Grafana - CMK raw

### ISSUE THREAD

**Issue by Doneven2012** [tribe29/grafana-checkmk-datasource#41]
Hi, I'm using Grafana with CheckMK Raw 2.0.0p6 and I haven't had any luck when it comes to complex graphs, it doesn't seem like I am the only one: https://forum.checkmk.com/t/checkmk-raw-with-grafana-combined-graph-graph-field-not-selectable/25181/14

The graph preview always seems to stay empty even though I have multiple weeks worth of data on my checkmk server, everything else seems to work, including **predefined graphs** and **single metrics**. 

In case it might be useful, whatever combination of host and service regex I use, the graph field seems to stay empty. Is there something I'm forgetting or does it work for anyone else? 
![image](https://user-images.githubusercontent.com/37813014/127919132-87f11db2-b057-4aaf-ab97-7a44e59f6085.png)

Thank you!

**Comment by ronaldocz** [comment]
I'm having the same problem on CMK Raw2.0.0p9, even trying to set it on the JSON doesn't work

**Comment by Doneven2012** [comment]
I tried using the same hosts and same grafana server but created a free checkmk instance (Enterprise edition but 10 hosts max) on docket and that worked. 

I feel like it's a limitation of the raw edition which is annoying but understandable. It would be nice to have confirmation though.

**Comment by ronaldocz** [comment]
It's weird because checkmk always points it out if the feature is only available for Enterprise.

I'm thinking of trying it using an older Grafana version...

**Comment by Doneven2012** [comment]
Exactly what I thought at first. Let me what happens if you end up testing it. I might start looking into it at some point since I have other things to add to our grafana.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by ronaldocz** [comment]
I have an old Grafana v5.3.1 () running so I just tested it, but sadly I got the same behaviour.

**Comment by Doneven2012** [comment]
I'm going to assume this is a premium feature. Hopefully someone can confirm (or deny) that. Else we'll see if that becomes available one day.
________________________________

**Comment by Titan-C** [comment]
Combined graphs are not part of the RAW edition, thus the Grafana connector cannot query that endpoint.
