### ISSUE TITLE
 plugin does not work with Grafana v8.3.0.

### ISSUE THREAD

**Issue by Leenders-IT** [tribe29/grafana-checkmk-datasource#52]
Good evening, 

I have noticed that the plugin does not work with Grafana v8.3.0. When is an update planned here?

**Comment by godspeed-you** [comment]
We are currently looking to add the compatibility in our upcoming rewrite. This rewrite has the same problems until now. I will close this issue, as soon as we solved the problems with the new version. Last information has been, that Grafana itself has an issue, which needs to be fixed first. After that, we can take a look on our side.

**Comment by Titan-C** [comment]
The last version it work is 8.1.7. On Grafana 8.2 grafana changed how plugins are loaded, to offer a faster load. Yet foreign plugins stopped being loaded. It has nothing to do with the signature of the plugin. We still wait for Grafana to provide a fix on their side.

**Comment by spacyt** [comment]
Hello,

is there some update. I want to use our Checkmk Installation with 8.2.

THX
Klaus

**Comment by yoannsaludes** [comment]
Hi there,
supporting 8.2+ would be very much appreciated.
I am running 8.3 and am ready to test if it can help.

**Comment by Titan-C** [comment]
It would help us a lot if you share how are you installing Grafana and the checkmk plugin. We just had success getting Grafana 8.3.4 installed on a docker container to load our plugin same as described in our guide https://docs.checkmk.com/latest/en/grafana.html#_special_features_from_grafana_8_0 without any change to our plugin, it just started working again. However, on that same Grafana version installed locally on Ubuntu the plugin is still not found. We don't yet understand what is going on with Grafana.

Are you using other foreign plugins in Grafana? Do they load while our plugin doesn't? Can you tell us which plugins are they, we can then look at them to see which changes might be necessary on our side.

**Comment by Titan-C** [comment]
We have moved forward in our debugging. It seems in our case that the issue actually arises from the new systemd configuration for grafana>8.2

If any of your local plugins is located in /home, /root, /run/user, or has a symlink to those places. Plugin loading will fail. Solution is either put your plugins in the directory outside of those and make that your grafana plugins_dir or change on the systemd startscript the config ProtectHome to ProtectHome=false or ProtectHome=read-only
