### ISSUE TITLE
data source does not appear in grafana

### ISSUE THREAD

**Issue by rimkov** [tribe29/grafana-checkmk-datasource#59]
Hello,
i'm using grafana 8.5.2 (docker) and i followed the check_mk documentation with the git clone method but the data source does not appear in grafana :(
https://docs.checkmk.com/latest/en/grafana.html
what could i have forgotten ?

thank you for your help :)

**Comment by bloep** [comment]
I had the same problem with my Docker setup. 
The problem for me was that since my configuration was almost empty, I didn't have the predefined sections in the .ini file.

It worked for me by making the
```
allow_loading_unsigned_plugins = checkmk-datasource
```
to 
```
[plugins]
allow_loading_unsigned_plugins = checkmk-datasource
```

**Comment by rimkov** [comment]
Hi Marcel,

Thank you for your reply, but i already have these lines :/.
I found in container logs that the plugin is skipped because he is
unsigned, so maybe a grafana issue ?! I'll check.

Le sam. 14 mai 2022, 13:18, Marcel Kuhmann ***@***.***> a
écrit :

**Comment by rimkov** [comment]
it seems that the plugin ID is not checkmk-datasource but tribe-29-checkmk-datasource ! after compilation everything is ok. checkmk documentation is not correct.

**Comment by BenediktSeidl** [comment]
You followed the 2.0.0 version of the documentation, https://docs.checkmk.com/master/en/grafana.html should describe the correct way to set up the data source but it's still work in progress.
I've created two internal issues for our knowledge-team to update the documentation to make it more clear which version of the data source plugin will be installed.
