### ISSUE TITLE
Add quick test setup guide to readme

### ISSUE THREAD

**Issue by LarsMichelsen** [tribe29/grafana-checkmk-datasource#6]
Possible contents:

1. Download & setup check_mk container like this: TODO
2. Open Check_MK GUI
3. Add a single host to Check_MK and discover the services
4. Get automation user credentials: WATO > Users > automation
4. Checkout grafana-checkmk-datasource to e.g. /home/lm/git/grafana-checkmk-datasource
5. Start grafana like this: docker run -d -p 3000:3000 -v /home/lm/git/grafana-checkmk-datasource/dist:/var/lib/grafana/plugins/checkmk-datasource grafana/grafana
6. Login to Grafana with admin:admin: http://localhost:3000/
7. Configure Check_MK data source (Insert URL and credentials)
8. Configure first graph

**Comment by cbmueller** [comment]
Added in 6303cc4d7221229b12eb966f27f61591c936e0ce
