### ISSUE TITLE
Hostname in Legend

### ISSUE THREAD

**Issue by ilabrovic** [tribe29/grafana-checkmk-datasource#61]
Hi, tested with both CheckMK RAW 2.0.latest (v25) and Raw running CheckMK RAW 2.1.latest.
Created a new Panel with CPU load query from 2 servers:
Service: CPU load
Graph type: Single Metric
Metric: CPU load average of last minute

Both queries work and show the same "CPU load average of the last minute" description in the legend.
How can I change that legend into the hostname from which it belongs to?
Someone suggested to add :by hostname or use group by hostname, but there is no free form field to add this to the query.

Help needed.

regards,
Ivan.

 
![image](https://user-images.githubusercontent.com/32865814/170886156-35011e32-137c-4607-9149-6e16506b0559.png)

**Comment by ilabrovic** [comment]
Sorry, probably same issue as #60 Hostname in title (RAW edition) by jplitza

**Comment by BenediktSeidl** [comment]
Yes. I will close this one as a duplicate of #61 but would encourage you to leave a :+1: on #61, so we know this is an issue multiple people are interested in.
