### ISSUE TITLE
Send datasource to grafana for review

### ISSUE THREAD

**Issue by LarsMichelsen** [tribe29/grafana-checkmk-datasource#7]
@cbmueller What do we need to do before we can submit this?

**Comment by cbmueller** [comment]
Should be fine as is.
https://grafana.com/docs/plugins/developing/plugin-review-guidelines/

**Comment by LarsMichelsen** [comment]
We don't need the API calls in Check_MK for the review. Do we? They are currently in review and will be added ~tomorrow.

Please check/fix #1 first. Can you please initiate the process like described here?: https://github.com/grafana/grafana-plugin-repository

**Comment by LarsMichelsen** [comment]
We’ve merged the needed API calls to the official Check_MK branches.

Upcoming releases, starting with 1.5.0p16, will be able to use the datasource.

**Comment by cbmueller** [comment]
See https://github.com/grafana/grafana-plugin-repository/pull/421
