### ISSUE TITLE
Tribe29 Logo not shown due to name mismatch

### ISSUE THREAD

**Issue by avantasia1975** [tribe29/grafana-checkmk-datasource#70]
Entry in dist/plugins.json points to img/checkmk_logo.svg but the actual file type is png. 
So the checkmk logo is not shown in Grafana. 
![Screenshot_2022-08-05_11-39-45](https://user-images.githubusercontent.com/65665594/183052549-99eb083d-de4a-409b-ac14-db1075fb9a03.png)
![Screenshot_2022-08-05_11-39-20](https://user-images.githubusercontent.com/65665594/183052551-a690d2eb-3ab7-4c2a-9405-e159ab507412.png)

I copied the svg file from src/img/ to dist/img and all works as expected. 
![Screenshot_2022-08-05_11-40-44](https://user-images.githubusercontent.com/65665594/183052725-e62445cc-02ab-4f9a-be7c-2f26d8e32079.png)

**Comment by BenediktSeidl** [comment]
Thanks a lot for the report! There is a problem in our release mechanism.
Expect a 2.0.1 release today, that will fix this issue.

**Comment by BenediktSeidl** [comment]
I just released version 2.0.1 to fix this problem. Thanks a lot for your detailed report.
