### ISSUE TITLE
Panel editor: Improve error reporting when API calls fail

### ISSUE THREAD

**Issue by LarsMichelsen** [tribe29/grafana-checkmk-datasource#8]
In case an API call fails it reports back a structure like this:

```
{"result": "Check_MK exception: Currently not supported with this Check_MK Edition", "result_code": 1}
```

Can we show the error messages of the result_code=1 responses to the use in the panel editor?

**Comment by cbmueller** [comment]
Implemented in 83ba322f7b515b27d335e06ded590e5dabb3eb34.
