### ISSUE TITLE
Graph not found for some common metrics

### ISSUE THREAD

**Issue by rimkov** [tribe29/grafana-checkmk-datasource#82]
I'm trying to create a dashboard for some hosts monitored by check_mk raw edition.
checkmk hosts fetching is working but when i'm trying to display some metrics for example related to RAM, grafana returns me "graph not found". i tried with "Single metric" and "Template" graph type and i tried with RAM used and RAM installed. 

what does this message means ? thank you for your support
(i'm using the latest release 2.0.2)

**Comment by BenediktSeidl** [comment]
We will need more information to be able to help you on this issue.
* Can you display any other metric?
* Can you verify this metric is available in checkmk?
* Which version of checkmk are you using?

Can you share a screenshot of your query, the error message and the "Query inspector"?

![2022-10-12_11-54](https://user-images.githubusercontent.com/1055738/195312468-4f18a5f0-193d-486a-bc39-4c6bbd7a3f80.png)

![2022-10-12_11-53](https://user-images.githubusercontent.com/1055738/195312508-ea3d0cfd-ab05-42e1-a099-af6ed67c4dc0.png)

**Comment by rimkov** [comment]
you are right, I'm sorry.... your answer has just provided a solution for the used ram :) => I tried with the "RAM Used" metric while you tried with "Used RAM"; so i retried with Used RAM and i've got the graph.

i'm using CheckMk 2.0.0p19(CRE)
i have all memory metrics in check_mk :

![image](https://user-images.githubusercontent.com/2571934/195327568-af8627b0-dab7-4f6b-a45c-89c1876979b2.png)

RAM + Swap Overview is working : the graph id is `\"graph_id\":\"ram_swap_overview\"}]`

![image](https://user-images.githubusercontent.com/2571934/195328825-0ed894a7-c3a3-43e3-99e6-aea91df0e45d.png)

but not RAM + Swap used, the graph id is `\"graph_id\":\"ram_swap_used\"}]`
i think they are the same metrics but we have to choose the good template ?

![image](https://user-images.githubusercontent.com/2571934/195333348-1838c13c-9011-4aa0-9cd8-9cca8dc66f7e.png)


for example we have several templates for CPU Utilization :

![image](https://user-images.githubusercontent.com/2571934/195332942-36fd30de-b674-4d3e-90ed-38e2791a0eea.png)

the one who is working for me is the graph_id `cpu_utilization_5_util`, the 7th of the list....

can you tell me when should we choose the type of graph template or single metric ?

maybe everything is normal after all? thank you for your help

**Comment by BenediktSeidl** [comment]
This seems to be an issue with checkmk 2.0.0 which is not supported by version 2 of grafana-checkmk-datasource. (There is no connection between versioning of checkmk and versioning of grafana-checkmk-datasource).

As stated in the README.md:
> The plugin requires Checkmk >= 2.1.0 and Grafana >= 8.0
> (It is possible query data from Checkmk >= 2.0.0p20 but host and service dropdowns are not constrained by other active filters and single metric graphs do not work with Checkmk Raw Edition)

We are aware of the fact that grafana-checkmk-datasource "kind of works" with checkmk 2.0.0, but sadly we have no time to properly support it. I would recommend updating to 2.1.0

**Comment by rimkov** [comment]
sorry I had not seen this comment. no problem, the plugin works a minimum and it can wait for a cmk update. thanks again.
